/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'hero-slides': HeroSlide;
    treatments: Treatment;
    testimonials: Testimonial;
    videos: Video;
    'blog-categories': BlogCategory;
    'blog-posts': BlogPost;
    gallery: Gallery;
    faqs: Faq;
    'support-topics': SupportTopic;
    pages: Page;
    'medical-kits': MedicalKit;
    'expense-categories': ExpenseCategory;
    expenses: Expense;
    patients: Patient;
    'patient-inquiries': PatientInquiry;
    'patient-appointments': PatientAppointment;
    'consultation-records': ConsultationRecord;
    'treatment-plans': TreatmentPlan;
    'patient-medicines': PatientMedicine;
    'patient-payments': PatientPayment;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'hero-slides': HeroSlidesSelect<false> | HeroSlidesSelect<true>;
    treatments: TreatmentsSelect<false> | TreatmentsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'support-topics': SupportTopicsSelect<false> | SupportTopicsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'medical-kits': MedicalKitsSelect<false> | MedicalKitsSelect<true>;
    'expense-categories': ExpenseCategoriesSelect<false> | ExpenseCategoriesSelect<true>;
    expenses: ExpensesSelect<false> | ExpensesSelect<true>;
    patients: PatientsSelect<false> | PatientsSelect<true>;
    'patient-inquiries': PatientInquiriesSelect<false> | PatientInquiriesSelect<true>;
    'patient-appointments': PatientAppointmentsSelect<false> | PatientAppointmentsSelect<true>;
    'consultation-records': ConsultationRecordsSelect<false> | ConsultationRecordsSelect<true>;
    'treatment-plans': TreatmentPlansSelect<false> | TreatmentPlansSelect<true>;
    'patient-medicines': PatientMedicinesSelect<false> | PatientMedicinesSelect<true>;
    'patient-payments': PatientPaymentsSelect<false> | PatientPaymentsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'contact-information': ContactInformation;
    'social-media': SocialMedia;
    'clinic-timings': ClinicTiming;
    'whatsapp-settings': WhatsappSetting;
    'homepage-settings': HomepageSetting;
    'seo-defaults': SeoDefault;
    'about-doctor': AboutDoctor;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'contact-information': ContactInformationSelect<false> | ContactInformationSelect<true>;
    'social-media': SocialMediaSelect<false> | SocialMediaSelect<true>;
    'clinic-timings': ClinicTimingsSelect<false> | ClinicTimingsSelect<true>;
    'whatsapp-settings': WhatsappSettingsSelect<false> | WhatsappSettingsSelect<true>;
    'homepage-settings': HomepageSettingsSelect<false> | HomepageSettingsSelect<true>;
    'seo-defaults': SeoDefaultsSelect<false> | SeoDefaultsSelect<true>;
    'about-doctor': AboutDoctorSelect<false> | AboutDoctorSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides".
 */
export interface HeroSlide {
  id: number;
  eyebrow?: string | null;
  heading: string;
  description: string;
  image: number | Media;
  ctaLabel?: string | null;
  ctaLink?: string | null;
  order: number;
  active: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "treatments".
 */
export interface Treatment {
  id: number;
  title: string;
  summary: string;
  /**
   * Short initials or symbol shown on the card.
   */
  iconLabel?: string | null;
  image?: (number | null) | Media;
  order: number;
  active: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  patientName: string;
  testimonial: string;
  rating?: number | null;
  location?: string | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  title: string;
  description?: string | null;
  url: string;
  platform: 'youtube' | 'instagram';
  thumbnail?: (number | null) | Media;
  publishedAt?: string | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  excerpt: string;
  content: string;
  featuredImage?: (number | null) | Media;
  category?: (number | null) | BlogCategory;
  publishedAt?: string | null;
  seo?: {
    /**
     * Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Recommended: 140–160 characters.
     */
    description?: string | null;
    canonicalURL?: string | null;
    shareImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  title: string;
  image: number | Media;
  caption?: string | null;
  category?: string | null;
  order: number;
  active: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  category?: string | null;
  order: number;
  active: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-topics".
 */
export interface SupportTopic {
  id: number;
  title: string;
  slug: string;
  eyebrow?: string | null;
  summary: string;
  overview: string;
  discussionPoints?:
    | {
        point: string;
        id?: string | null;
      }[]
    | null;
  whenToSeekCare: string;
  featuredImage?: (number | null) | Media;
  order?: number | null;
  seo?: {
    /**
     * Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Recommended: 140–160 characters.
     */
    description?: string | null;
    canonicalURL?: string | null;
    shareImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  pageType: 'general' | 'consultation' | 'legal';
  summary: string;
  content: string;
  highlights?:
    | {
        highlight: string;
        id?: string | null;
      }[]
    | null;
  showAppointmentCTA?: boolean | null;
  seo?: {
    /**
     * Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Recommended: 140–160 characters.
     */
    description?: string | null;
    canonicalURL?: string | null;
    shareImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medical-kits".
 */
export interface MedicalKit {
  id: number;
  title: string;
  slug: string;
  description: string;
  /**
   * Internal editorial keywords, separated by commas. Do not stuff these into visible content.
   */
  keywords?: string | null;
  image: number | Media;
  price: number;
  currency: 'PKR' | 'USD' | 'GBP' | 'AED';
  benefits: {
    benefit: string;
    id?: string | null;
  }[];
  safetyNotice: string;
  featured: boolean;
  active: boolean;
  order: number;
  seo?: {
    /**
     * Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Recommended: 140–160 characters.
     */
    description?: string | null;
    canonicalURL?: string | null;
    shareImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expense-categories".
 */
export interface ExpenseCategory {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  monthlyBudget?: number | null;
  active: boolean;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Record and organize clinic operating expenses. Use filters to review expenses by date, category, status, or payment method.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expenses".
 */
export interface Expense {
  id: number;
  title?: string | null;
  category: number | ExpenseCategory;
  expenseDate: string;
  amount: number;
  currency: 'PKR';
  status: 'paid' | 'pending' | 'reimbursed' | 'cancelled';
  paymentMethod: 'cash' | 'bank-transfer' | 'card' | 'easypaisa' | 'jazzcash' | 'cheque' | 'other';
  vendor?: string | null;
  referenceNumber?: string | null;
  receipt?: (number | null) | Media;
  recurring: boolean;
  recurrence?: ('weekly' | 'monthly' | 'quarterly' | 'yearly') | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patients".
 */
export interface Patient {
  id: number;
  patientCode?: string | null;
  fullName: string;
  whatsappNumber: string;
  location: string;
  dateOfBirth?: string | null;
  gender?: ('female' | 'male' | 'other') | null;
  address?: string | null;
  guardianName?: string | null;
  guardianRelationship?: string | null;
  emergencyContact?: string | null;
  status: 'prospective' | 'active' | 'inactive' | 'archived';
  preferredConsultation?: ('video' | 'physical' | 'not-specified') | null;
  source: string;
  consentToContact: boolean;
  lastInquiryAt?: string | null;
  reportedAllergies?: string | null;
  reportedDiagnoses?: string | null;
  currentPrescribedMedicines?: string | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patient-inquiries".
 */
export interface PatientInquiry {
  id: number;
  patient: number | Patient;
  inquiryType: 'video-consultation' | 'physical-consultation' | 'general-inquiry' | 'medical-kit';
  source: string;
  message: string;
  productName?: string | null;
  quantity?: number | null;
  status: 'new' | 'contacted' | 'converted' | 'closed';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patient-appointments".
 */
export interface PatientAppointment {
  id: number;
  patient: number | Patient;
  appointmentDate: string;
  appointmentType: 'physical' | 'video';
  status: 'requested' | 'scheduled' | 'completed' | 'cancelled' | 'no-show';
  reason?: string | null;
  meetingDetails?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-records".
 */
export interface ConsultationRecord {
  id: number;
  patient: number | Patient;
  appointment?: (number | null) | PatientAppointment;
  consultationDate: string;
  consultationType?: ('physical' | 'video') | null;
  mainConcerns?: string | null;
  historyReported?: string | null;
  observations?: string | null;
  guidanceProvided?: string | null;
  privateClinicalNotes?: string | null;
  followUpDate?: string | null;
  documents?: (number | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "treatment-plans".
 */
export interface TreatmentPlan {
  id: number;
  patient: number | Patient;
  consultation?: (number | null) | ConsultationRecord;
  title: string;
  startDate?: string | null;
  status?: ('active' | 'completed' | 'paused' | 'discontinued') | null;
  objectives?: string | null;
  instructions?: string | null;
  reviewDate?: string | null;
  outcomeNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patient-medicines".
 */
export interface PatientMedicine {
  id: number;
  patient: number | Patient;
  consultation?: (number | null) | ConsultationRecord;
  medicineName: string;
  sourceType?: ('clinic-recommendation' | 'external-prescription' | 'supplement' | 'medical-kit') | null;
  strengthOrForm?: string | null;
  instructions?: string | null;
  frequency?: string | null;
  startDate?: string | null;
  endDate?: string | null;
  status?: ('active' | 'completed' | 'stopped') | null;
  fulfilment?: ('pending' | 'dispensed' | 'collected' | 'delivered') | null;
  safetyNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patient-payments".
 */
export interface PatientPayment {
  id: number;
  patient: number | Patient;
  appointment?: (number | null) | PatientAppointment;
  invoiceNumber?: string | null;
  description?: string | null;
  totalAmount: number;
  paidAmount: number;
  currency: 'PKR';
  status: 'unpaid' | 'partial' | 'paid' | 'refunded';
  paymentMethod?: ('cash' | 'bank-transfer' | 'card' | 'easypaisa' | 'jazzcash' | 'other') | null;
  paymentDate?: string | null;
  receipt?: (number | null) | Media;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'hero-slides';
        value: number | HeroSlide;
      } | null)
    | ({
        relationTo: 'treatments';
        value: number | Treatment;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: number | BlogCategory;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'support-topics';
        value: number | SupportTopic;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'medical-kits';
        value: number | MedicalKit;
      } | null)
    | ({
        relationTo: 'expense-categories';
        value: number | ExpenseCategory;
      } | null)
    | ({
        relationTo: 'expenses';
        value: number | Expense;
      } | null)
    | ({
        relationTo: 'patients';
        value: number | Patient;
      } | null)
    | ({
        relationTo: 'patient-inquiries';
        value: number | PatientInquiry;
      } | null)
    | ({
        relationTo: 'patient-appointments';
        value: number | PatientAppointment;
      } | null)
    | ({
        relationTo: 'consultation-records';
        value: number | ConsultationRecord;
      } | null)
    | ({
        relationTo: 'treatment-plans';
        value: number | TreatmentPlan;
      } | null)
    | ({
        relationTo: 'patient-medicines';
        value: number | PatientMedicine;
      } | null)
    | ({
        relationTo: 'patient-payments';
        value: number | PatientPayment;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slides_select".
 */
export interface HeroSlidesSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  description?: T;
  image?: T;
  ctaLabel?: T;
  ctaLink?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "treatments_select".
 */
export interface TreatmentsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  iconLabel?: T;
  image?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  patientName?: T;
  testimonial?: T;
  rating?: T;
  location?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  url?: T;
  platform?: T;
  thumbnail?: T;
  publishedAt?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  category?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalURL?: T;
        shareImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  image?: T;
  caption?: T;
  category?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-topics_select".
 */
export interface SupportTopicsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  eyebrow?: T;
  summary?: T;
  overview?: T;
  discussionPoints?:
    | T
    | {
        point?: T;
        id?: T;
      };
  whenToSeekCare?: T;
  featuredImage?: T;
  order?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalURL?: T;
        shareImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  pageType?: T;
  summary?: T;
  content?: T;
  highlights?:
    | T
    | {
        highlight?: T;
        id?: T;
      };
  showAppointmentCTA?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalURL?: T;
        shareImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medical-kits_select".
 */
export interface MedicalKitsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  keywords?: T;
  image?: T;
  price?: T;
  currency?: T;
  benefits?:
    | T
    | {
        benefit?: T;
        id?: T;
      };
  safetyNotice?: T;
  featured?: T;
  active?: T;
  order?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalURL?: T;
        shareImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expense-categories_select".
 */
export interface ExpenseCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  monthlyBudget?: T;
  active?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expenses_select".
 */
export interface ExpensesSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  expenseDate?: T;
  amount?: T;
  currency?: T;
  status?: T;
  paymentMethod?: T;
  vendor?: T;
  referenceNumber?: T;
  receipt?: T;
  recurring?: T;
  recurrence?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patients_select".
 */
export interface PatientsSelect<T extends boolean = true> {
  patientCode?: T;
  fullName?: T;
  whatsappNumber?: T;
  location?: T;
  dateOfBirth?: T;
  gender?: T;
  address?: T;
  guardianName?: T;
  guardianRelationship?: T;
  emergencyContact?: T;
  status?: T;
  preferredConsultation?: T;
  source?: T;
  consentToContact?: T;
  lastInquiryAt?: T;
  reportedAllergies?: T;
  reportedDiagnoses?: T;
  currentPrescribedMedicines?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patient-inquiries_select".
 */
export interface PatientInquiriesSelect<T extends boolean = true> {
  patient?: T;
  inquiryType?: T;
  source?: T;
  message?: T;
  productName?: T;
  quantity?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patient-appointments_select".
 */
export interface PatientAppointmentsSelect<T extends boolean = true> {
  patient?: T;
  appointmentDate?: T;
  appointmentType?: T;
  status?: T;
  reason?: T;
  meetingDetails?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "consultation-records_select".
 */
export interface ConsultationRecordsSelect<T extends boolean = true> {
  patient?: T;
  appointment?: T;
  consultationDate?: T;
  consultationType?: T;
  mainConcerns?: T;
  historyReported?: T;
  observations?: T;
  guidanceProvided?: T;
  privateClinicalNotes?: T;
  followUpDate?: T;
  documents?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "treatment-plans_select".
 */
export interface TreatmentPlansSelect<T extends boolean = true> {
  patient?: T;
  consultation?: T;
  title?: T;
  startDate?: T;
  status?: T;
  objectives?: T;
  instructions?: T;
  reviewDate?: T;
  outcomeNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patient-medicines_select".
 */
export interface PatientMedicinesSelect<T extends boolean = true> {
  patient?: T;
  consultation?: T;
  medicineName?: T;
  sourceType?: T;
  strengthOrForm?: T;
  instructions?: T;
  frequency?: T;
  startDate?: T;
  endDate?: T;
  status?: T;
  fulfilment?: T;
  safetyNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patient-payments_select".
 */
export interface PatientPaymentsSelect<T extends boolean = true> {
  patient?: T;
  appointment?: T;
  invoiceNumber?: T;
  description?: T;
  totalAmount?: T;
  paidAmount?: T;
  currency?: T;
  status?: T;
  paymentMethod?: T;
  paymentDate?: T;
  receipt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  doctorName: string;
  clinicType: string;
  tagline?: string | null;
  domain: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-information".
 */
export interface ContactInformation {
  id: number;
  phone: string;
  email?: string | null;
  address: string;
  mapURL?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-media".
 */
export interface SocialMedia {
  id: number;
  facebookURL?: string | null;
  instagramURL?: string | null;
  youtubeURL?: string | null;
  tiktokURL?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinic-timings".
 */
export interface ClinicTiming {
  id: number;
  schedule?:
    | {
        days: string;
        hours: string;
        closed?: boolean | null;
        id?: string | null;
      }[]
    | null;
  appointmentNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whatsapp-settings".
 */
export interface WhatsappSetting {
  id: number;
  enabled: boolean;
  number: string;
  buttonLabel: string;
  prefilledMessage?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-settings".
 */
export interface HomepageSetting {
  id: number;
  about: {
    image?: (number | null) | Media;
    heading: string;
    text: string;
    qualifications?: string | null;
    ctaLabel?: string | null;
    ctaLink?: string | null;
    secondaryCTALabel?: string | null;
    secondaryCTALink?: string | null;
  };
  consultationOptions: {
    eyebrow?: string | null;
    heading: string;
    intro?: string | null;
    videoConsultation: {
      title: string;
      description: string;
      benefits: {
        benefit: string;
        id?: string | null;
      }[];
      ctaLabel: string;
    };
    clinicVisit: {
      title: string;
      description: string;
      benefits: {
        benefit: string;
        id?: string | null;
      }[];
      ctaLabel: string;
    };
  };
  developmentalSupport: {
    heading: string;
    text: string;
    concerns?:
      | {
          concern: string;
          url?: string | null;
          id?: string | null;
        }[]
      | null;
    ctaLabel?: string | null;
    ctaLink?: string | null;
  };
  videosHeading: string;
  testimonialsHeading: string;
  blogHeading: string;
  contactCTA: {
    heading: string;
    text?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults".
 */
export interface SeoDefault {
  id: number;
  metaTitle: string;
  metaDescription: string;
  shareImage?: (number | null) | Media;
  noIndex?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-doctor".
 */
export interface AboutDoctor {
  id: number;
  pageTitle: string;
  doctorName: string;
  image?: (number | null) | Media;
  intro: string;
  biography: string;
  /**
   * Only publish verified qualifications and professional memberships.
   */
  qualifications: string;
  areasOfFocus?:
    | {
        area: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Internal editorial keywords. Search engines do not use a meta-keywords tag.
   */
  keywords?: string | null;
  mapHeading?: string | null;
  /**
   * Address or place query used to create the embedded Google map.
   */
  mapQuery?: string | null;
  seo?: {
    /**
     * Recommended: 50–60 characters.
     */
    title?: string | null;
    /**
     * Recommended: 140–160 characters.
     */
    description?: string | null;
    canonicalURL?: string | null;
    shareImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  doctorName?: T;
  clinicType?: T;
  tagline?: T;
  domain?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-information_select".
 */
export interface ContactInformationSelect<T extends boolean = true> {
  phone?: T;
  email?: T;
  address?: T;
  mapURL?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "social-media_select".
 */
export interface SocialMediaSelect<T extends boolean = true> {
  facebookURL?: T;
  instagramURL?: T;
  youtubeURL?: T;
  tiktokURL?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clinic-timings_select".
 */
export interface ClinicTimingsSelect<T extends boolean = true> {
  schedule?:
    | T
    | {
        days?: T;
        hours?: T;
        closed?: T;
        id?: T;
      };
  appointmentNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "whatsapp-settings_select".
 */
export interface WhatsappSettingsSelect<T extends boolean = true> {
  enabled?: T;
  number?: T;
  buttonLabel?: T;
  prefilledMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-settings_select".
 */
export interface HomepageSettingsSelect<T extends boolean = true> {
  about?:
    | T
    | {
        image?: T;
        heading?: T;
        text?: T;
        qualifications?: T;
        ctaLabel?: T;
        ctaLink?: T;
        secondaryCTALabel?: T;
        secondaryCTALink?: T;
      };
  consultationOptions?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        intro?: T;
        videoConsultation?:
          | T
          | {
              title?: T;
              description?: T;
              benefits?:
                | T
                | {
                    benefit?: T;
                    id?: T;
                  };
              ctaLabel?: T;
            };
        clinicVisit?:
          | T
          | {
              title?: T;
              description?: T;
              benefits?:
                | T
                | {
                    benefit?: T;
                    id?: T;
                  };
              ctaLabel?: T;
            };
      };
  developmentalSupport?:
    | T
    | {
        heading?: T;
        text?: T;
        concerns?:
          | T
          | {
              concern?: T;
              url?: T;
              id?: T;
            };
        ctaLabel?: T;
        ctaLink?: T;
      };
  videosHeading?: T;
  testimonialsHeading?: T;
  blogHeading?: T;
  contactCTA?:
    | T
    | {
        heading?: T;
        text?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults_select".
 */
export interface SeoDefaultsSelect<T extends boolean = true> {
  metaTitle?: T;
  metaDescription?: T;
  shareImage?: T;
  noIndex?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-doctor_select".
 */
export interface AboutDoctorSelect<T extends boolean = true> {
  pageTitle?: T;
  doctorName?: T;
  image?: T;
  intro?: T;
  biography?: T;
  qualifications?: T;
  areasOfFocus?:
    | T
    | {
        area?: T;
        id?: T;
      };
  keywords?: T;
  mapHeading?: T;
  mapQuery?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        canonicalURL?: T;
        shareImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}